/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mnist;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appDoesStart() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest);
    }
}
